// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddMemory(arg1:string):Promise<string>;

export function DeleteMemory(arg1:string):Promise<void>;

export function GetConversations():Promise<Array<main.ConversationSummary>>;

export function GetMemories():Promise<Array<main.MemoryItem>>;

export function GetMessages(arg1:string):Promise<Array<main.HistoryMessage>>;

export function GetPlatform():Promise<string>;

export function GetStatus():Promise<main.StatusInfo>;

export function ListModels():Promise<Array<string>>;

export function NewConversation():Promise<void>;

export function OpenInstallPage():Promise<void>;

export function PopOut():Promise<void>;

export function SendMessage(arg1:main.ChatRequest):Promise<void>;

export function SetActiveConversation(arg1:string):Promise<void>;
