// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetPlatform():Promise<string>;

export function GetStatus():Promise<main.StatusInfo>;

export function ListModels():Promise<Array<string>>;

export function OpenInstallPage():Promise<void>;

export function PopOut():Promise<void>;

export function SendMessage(arg1:main.ChatRequest):Promise<void>;
