// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMemory(arg1) {
  return window['go']['main']['App']['AddMemory'](arg1);
}

export function DeleteMemory(arg1) {
  return window['go']['main']['App']['DeleteMemory'](arg1);
}

export function GetConversations() {
  return window['go']['main']['App']['GetConversations']();
}

export function GetMemories() {
  return window['go']['main']['App']['GetMemories']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function NewConversation() {
  return window['go']['main']['App']['NewConversation']();
}

export function OpenInstallPage() {
  return window['go']['main']['App']['OpenInstallPage']();
}

export function PopOut() {
  return window['go']['main']['App']['PopOut']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetActiveConversation(arg1) {
  return window['go']['main']['App']['SetActiveConversation'](arg1);
}
